version: "3"
services:
  front:
    environment:
      domainAddress: http://localhost:7000
    volumes:
      - ../front/src:/front/src:cached
    expose:
      - 7000
    ports:
      - 7000:7000
    networks:
      - fake
    build: ../front
    container_name: front

networks:
  fake:
    driver: bridge